name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]

# Permisos necesarios para publicar en Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Inspección de Artefactos (QA & Observabilidad)
        run: ls -laR dist/ || echo "La carpeta dist no existe"

      # Control de calidad: Desactivamos la copia temporalmente para aislar la causa raíz
      # - name: Copy index.html to 404.html
      #   run: cp dist/client/index.html dist/client/404.html

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Basado en tus logs anteriores, aquí es donde Vite guarda tu web
          path: './dist/client'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
